create database Gungeon;
use Gungeon;
create table guns (
  itemid int,
  Name varchar(255),
  Description text,
  Quote varchar(255),
  primary key (itemid)
);

create table Admin (
    AdminID int,
    Username varchar(255),
    PwHash varchar(255),
	salt varchar(255),
    Primary Key (AdminID)
);

insert into guns (itemid, Name, Description, Quote) values
(1,"Rusty Sidearm","The Rusty Sidearm was brought to the Gungeon by the Hunter.  Despite its extremely dated design and some signs of rust, this gun appears relatively new. Very strange... ","Still Works. Mostly."),
(2,"Marine Sidearm","The Marine Sidearm was brought to the Gungeon by a low-ranking Primerdyne soldier.  Though this gun appears sturdy, it has been known to fail when it is most needed. ","Always With You"),
(3,"Rogue Special","The Rogue Special, given to the Pilot by his partner. It's never let him down.  This hip shooter has been known to fire half-cocked and often gets itself into more trouble than it can handle. ","Underhanded And Efficient"),
(4,"Budget Revolver","This Budget Revolver was brought to the Gungeon by an infamous fugitive.  Provided by the Hegemony Regional Magistrate. The Convict won their plea to face the Gungeon in lieu of life imprisonment; undo their crimes, or face an eternity in Gungeon. With no cost to the state, it was an acceptable arrangement.  Cheaply made and prone to jams, the Budget Revolver used by only the most desperate Gungeoneers. ", "Affordable Arms"),
(5,"Dart Gun","Just because children are young, doesn't mean they don't have pasts they would like to change. Perhaps some young soul wished to make sure his or her sibling took the blame for spilling grape juice on the couch. Much less worthy causes have been championed in the Gungeon. ","Sticky"),
(6,"Robot’s Right Hand","The right hand of an assault robot that fled to the Gungeon.  It is a simple projectile delivery system. Reliable, but it's short barrel is lacking in intricacy. Under the control of a targeting AI it becomes fearsome indeed. ","Built To Kill"),
(7,"Blasphemy","Betrayer!","To The Point"),
(8,"Pea Shooter", "Traditionally given to Gungeoneers when they first arrive at the Gungeon. It is incredibly weak. ", "Baby's First Gun"),
(9, "38 Special", "The sidearm of choice for investigative efforts. ", "For The Inquisitive"),
(10, "Derringer", "This tiny pistol packs a correspondingly small punch, but it is well-known for getting its wielders out of tight spots. ", "One Last Trick"),
(11, "Unfinished Gun", "This gun is still in the process of being forged! It barely functions in its current state, but could be a viable choice in a truly desperate situation. A small hourglass is embossed on the cylinder. ", "Still Warm"),
(12, "Makarov", "The Makarov was brought to the Gungeon by a lost Cosmonaut. Some say that the brave, lost soul still wanders the Gungeon. This gun is no better or worse than any other gun. ", "The People's gun"),
(13, "M1911", "The ancient design fires simple lead projectiles from a moderately-sized clip. In the right hands, this weapon is a force to be reckoned with. ", "Classic"),
(14, "Magnum", "This gun is unusually filthy for a handgun in the Gungeon. The Gundead spend much of their time polishing and greasing guns, though they conspicuously leave the Magnum alone. ", "5 Shots Or 6?"),
(15, "Colt 1851", "An ancient example of fine guncraft, the Colt 1851 has been the gun of choice for many a nameless gunslinger.

Skilled wielders have been known to quickly fire multiple shots, though the technique has been mostly lost to time. ", "You Dig"),
(16, "", "", ""),
(17, "", "", "");
-- (18, "", "", ""),
-- (19, "", "", ""),
-- (20, "", "", ""),
-- (21, "", "", ""),
-- (22, "", "", ""),
-- (23, "", "", ""),
-- (24, "", "", ""),
-- (25, "", "", ""),
-- (26, "", "", ""),
-- (27, "", "", ""),
-- (28, "", "", ""),
-- (29, "", "", ""),
-- ("gun30", "", "", ""),
-- ("gun31", "", "", ""),
-- ("gun32", "", "", ""),
-- ("gun33", "", "", ""),
-- ("gun34", "", "", ""),
-- ("gun35", "", "", ""),
-- ("gun36", "", "", ""),
-- ("gun37", "", "", ""),
-- ("gun38", "", "", ""),
-- ("gun39", "", "", ""),
-- ("gun40", "", "", ""),
-- ("gun41", "", "", ""),
-- ("gun42", "", "", ""),
-- ("gun43", "", "", ""),
-- ("gun44", "", "", ""),
-- ("gun45", "", "", ""),
-- ("gun46", "", "", ""),
-- ("gun47", "", "", ""),
-- ("gun48", "", "", ""),
-- ("gun49", "", "", ""),
-- ("gun50", "", "", ""),
-- ("gun51", "", "", ""),
-- ("gun52", "", "", ""),
-- ("gun53", "", "", ""),
-- ("gun54", "", "", ""),
-- ("gun55", "", "", ""),
-- ("gun56", "", "", ""),
-- ("gun57", "", "", ""),
-- ("gun58", "", "", ""),
-- ("gun59", "", "", ""),
-- ("gun60", "", "", ""),
-- ("gun61", "", "", ""),
-- ("gun62", "", "", ""),
-- ("gun63", "", "", ""),
-- ("gun64", "", "", ""),
-- ("gun65", "", "", ""),
-- ("gun66", "", "", ""),
-- ("gun67", "", "", ""),
-- ("gun68", "", "", ""),
-- ("gun69", "", "", ""),
-- ("gun70", "", "", ""),
-- ("gun71", "", "", ""),
-- ("gun72", "", "", ""),
-- ("gun73", "", "", ""),
-- ("gun74", "", "", ""),
-- ("gun75", "", "", ""),
-- ("gun76", "", "", ""),
-- ("gun77", "", "", ""),
-- ("gun78", "", "", ""),
-- ("gun79", "", "", ""),
-- ("gun80", "", "", ""),
-- ("gun81", "", "", ""),
-- ("gun82", "", "", ""),
-- ("gun83", "", "", ""),
-- ("gun84", "", "", ""),
-- ("gun85", "", "", ""),
-- ("gun86", "", "", ""),
-- ("gun87", "", "", ""),
-- ("gun88", "", "", ""),
-- ("gun89", "", "", ""),
-- ("gun90", "", "", ""),
-- ("gun91", "", "", ""),
-- ("gun92", "", "", ""),
-- ("gun93", "", "", ""),
-- ("gun94", "", "", ""),
-- ("gun95", "", "", ""),
-- ("gun96", "", "", ""),
-- ("gun97", "", "", ""),
-- ("gun98", "", "", ""),
-- ("gun99", "", "", ""),
-- ("gun100", "", "", ""),
-- ("gun101", "", "", ""),
-- ("gun102", "", "", ""),
-- ("gun103", "", "", ""),
-- ("gun104", "", "", ""),
-- ("gun105", "", "", ""),
-- ("gun106", "", "", ""),
-- ("gun107", "", "", ""),
-- ("gun108", "", "", ""),
-- ("gun109", "", "", ""),
-- ("gun110", "", "", ""),
-- ("gun111", "", "", ""),
-- ("gun112", "", "", ""),
-- ("gun113", "", "", ""),
-- ("gun114", "", "", ""),
-- ("gun115", "", "", ""),
-- ("gun116", "", "", ""),
-- ("gun117", "", "", ""),
-- ("gun118", "", "", ""),
-- ("gun119", "", "", ""),
-- ("gun120", "", "", ""),
-- ("gun121", "", "", ""),
-- ("gun122", "", "", ""),
-- ("gun123", "", "", ""),
-- ("gun124", "", "", ""),
-- ("gun125", "", "", ""),
-- ("gun126", "", "", ""),
-- ("gun127", "", "", ""),
-- ("gun128", "", "", ""),
-- ("gun129", "", "", ""),
-- ("gun130", "", "", ""),
-- ("gun131", "", "", ""),
-- ("gun132", "", "", ""),
-- ("gun133", "", "", ""),
-- ("gun134", "", "", ""),
-- ("gun135", "", "", ""),
-- ("gun136", "", "", ""),
-- ("gun137", "", "", ""),
-- ("gun138", "", "", ""),
-- ("gun139", "", "", ""),
-- ("gun140", "", "", ""),
-- ("gun141", "", "", ""),
-- ("gun142", "", "", ""),
-- ("gun143", "", "", ""),
-- ("gun144", "", "", ""),
-- ("gun145", "", "", ""),
-- ("gun146", "", "", ""),
-- ("gun147", "", "", ""),
-- ("gun148", "", "", ""),
-- ("gun149", "", "", ""),
-- ("gun150", "", "", ""),
-- ("gun151", "", "", ""),
-- ("gun152", "", "", ""),
-- ("gun153", "", "", ""),
-- ("gun154", "", "", ""),
-- ("gun155", "", "", ""),
-- ("gun156", "", "", ""),
-- ("gun157", "", "", ""),
-- ("gun158", "", "", ""),
-- ("gun159", "", "", ""),
-- ("gun160", "", "", ""),
-- ("gun161", "", "", ""),
-- ("gun162", "", "", ""),
-- ("gun163", "", "", ""),
-- ("gun164", "", "", ""),
-- ("gun165", "", "", ""),
-- ("gun166", "", "", ""),
-- ("gun167", "", "", ""),
-- ("gun168", "", "", ""),
-- ("gun169", "", "", ""),
-- ("gun170", "", "", ""),
-- ("gun171", "", "", ""),
-- ("gun172", "", "", ""),
-- ("gun173", "", "", ""),
-- ("gun174", "", "", ""),
-- ("gun175", "", "", ""),
-- ("gun176", "", "", ""),
-- ("gun177", "", "", ""),
-- ("gun178", "", "", ""),
-- ("gun179", "", "", ""),
-- ("gun180", "", "", ""),
-- ("gun181", "", "", ""),
-- ("gun182", "", "", ""),
-- ("gun183", "", "", ""),
-- ("gun184", "", "", ""),
-- ("gun185", "", "", ""),
-- ("gun186", "", "", "");
-- ("A0008","Casey","A standard baseball bat, modified to hit bullets instead of balls. Launches enemy projectiles back with a vengeance!  Nothing can happen until you swing the bat. ","Casey.png","Batting .50");

-- drop table guns;
-- drop table Admin;